version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: transport_db

  mqtt_broker:
    image: eclipse-mosquitto
    container_name: mqtt_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt_config:/mosquitto/config
    command: mosquitto -c /mosquitto/config/mosquitto.conf

  middleware:
    build:
      context: ./middleware
    container_name: python_middleware
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - mqtt_broker
    volumes:
      - ./middleware:/app

  locust:
    build:
      context: .
      dockerfile: Dockerfile.locust
    ports:
      - "8089:8089"
    depends_on:
      - middleware

  sensor_emulators:
    build: ./sensor_emulators
    container_name: sensor_emulators
    depends_on:
      - mqtt_broker
    environment:
      - BROKER=mqtt_broker
    restart: always
    volumes:
      - ./sensor_emulators:/app

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  mongo_data:
  grafana_data:
