version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mqtt_broker:
    image: eclipse-mosquitto
    container_name: mqtt_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt_config:/mosquitto/config
    command: mosquitto -c /mosquitto/config/mosquitto.conf

  middleware:
    build:
      context: ./middleware
    container_name: python_middleware
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - mqtt_broker
    volumes:
      - ./middleware:/app

  locust:
    build:
      context: .
      dockerfile: Dockerfile.locust
    ports:
      - "8089:8089"  # Expose Locust web interface
    depends_on:
      - middleware  # Ensure the middleware is up before testing


  passenger_emulator:
    build:
      context: ./sensor_emulators
    container_name: passenger_emulator
    command: python passenger_emulator.py
    depends_on:
      - mqtt_broker
    environment:
      - BROKER=mqtt_broker
    volumes:
      - ./sensor_emulators:/app

  environment_emulator:
    build:
      context: ./sensor_emulators
    container_name: environment_emulator
    command: python environment_emulator.py
    depends_on:
      - mqtt_broker
    environment:
      - BROKER=mqtt_broker
    volumes:
      - ./sensor_emulators:/app

  gps_emulator:
    build:
      context: ./sensor_emulators
    container_name: gps_emulator
    command: python gps_emulator.py
    depends_on:
      - mqtt_broker
    environment:
      - BROKER=mqtt_broker
    volumes:
      - ./sensor_emulators:/app

volumes:
  mongo_data:
