global:
  scrape_interval: 15s  # Scrape targets every 15 seconds

scrape_configs:
  - job_name: 'flask_app_metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['python_middleware:8000'] 
